export const MenuList = [
    {
        type: "dropdown",
        title: "Dashboard",
        iconClass: "ph-duotone ph-house-line",
        name: "dashboard",
        badgeCount: 4,
        collapseId: "dashboard",
        path: '/dashboard',
        children: [
            {name: "Ecommerce", path: "/dashboard/ecommerce"},
            {name: "Project", path: "/dashboard/project"},
            {name: "Crypto", path: "/dashboard/crypto"},
            {name: "Education", path: "/dashboard/education"},
        ],
    },
    {
        type: "dropdown",
        iconClass: "ph-duotone ph-stack",
        collapseId: "apps",
        name: "apps",
        path: '/apps',
        children: [
            {name: "Calendar", path: "/apps/calendar"},
            {
                name: "Profile",
                path: "/",
                collapseId: "Profile-page",
                children: [
                    {name: "Profile", path: "/apps/profile-page/profile"},
                    {name: "Setting", path: "/apps/profile-page/setting"},
                ],
            },
            {
                name: "Projects Page",
                path: "/Apexcharts.html",
                collapseId: "projects-page",
                children: [
                    {name: "Projects", path: "/apps/projects-page/projects"},
                    {name: "Projects Details", path: "/apps/projects-page/project-details"},
                ],
            },
            {name: "To-Do", path: "/apps/todo"},
            {name: "Team", path: "/apps/team"},
            {name: "API", path: "/apps/api"},
            {
                name: "Ticket",
                path: "/Apexcharts.html",
                collapseId: "ticket-page",
                children: [
                    {name: "Ticket", path: "/apps/tickets/ticket"},
                    {name: "Ticket Details", path: "/apps/tickets/tickets-details"},
                ],
            },
            {
                name: "Email Page",
                path: "/Apexcharts.html",
                collapseId: "email-page",
                children: [
                    {name: "Email", path: "/apps/email-page/email"},
                    {name: "Read Email", path: "/apps/email-page/read-email"},
                ],
            },
            {
                name: "E-shop",
                path: "/Apexcharts.html",
                collapseId: "e-shop",
                children: [
                    {name: "Cart", path: "/apps/e-shop/cart"},
                    {name: "Product", path: "/apps/e-shop/product"},
                    {name: "Add Product", path: "/apps/e-shop/add-product"},
                    {name: "Product-Details", path: "/apps/e-shop/product-details"},
                    {name: "Product list", path: "/apps/e-shop/product-list"},
                    {name: "Orders", path: "/apps/e-shop/orders"},
                    {name: "Orders Details", path: "/apps/e-shop/orders-details"},
                    {name: "Orders List", path: "/apps/e-shop/orders-list"},
                    {name: "Checkout", path: "/apps/e-shop/checkout"},
                    {name: "Wishlist", path: "/apps/e-shop/wishlist"},
                ],
            },
            {name: "Invoice", path: "/apps/invoice"},
            {name: "Chat", path: "/apps/chat"},
            {name: "File Manager", path: "/apps/file-manager"},
            {name: "bookmark", path: "/apps/bookmark"},
            {name: "kanban board", path: "/apps/kanban-board"},
            {name: "Timeline", path: "/apps/timeline"},
            {name: "FAQ", path: "/apps/faq"},
            {name: "Pricing", path: "/apps/pricing"},
            {name: "Gallery", path: "/apps/gallery"},
            {
                name: "Blog Page",
                path: "/Apexcharts.html",
                collapseId: "blog-page",
                children: [
                    {name: "Blog", path: "/apps/blog-page/blog"},
                    {name: "Blog Details", path: "/apps/blog-page/blog-details"},
                    {name: "Add Blog", path: "/apps/blog-page/add-blog"},
                ],
            },
        ],
    },
    {
        name: "Widgets",
        path: '/widgets',
        iconClass: "ph-duotone ph-squares-four",
    },
    {
        type: "dropdown",
        title: "Component",
        iconClass: "ph-duotone ph-briefcase",
        name: "Ui Kits",
        collapseId: "ui-kits",
        path: '/ui-kits',
        children: [
            {name: "Cheatsheet", path: "/ui-kit/cheatsheet"},
            {name: "Alert", path: "/ui-kit/alert"},
            {name: "Badges", path: "/ui-kit/badges"},
            {name: "Buttons", path: "/ui-kit/buttons"},
            {name: "Cards", path: "/ui-kit/cards"},
            {name: "Dropdown", path: "/ui-kit/dropdown"},
            {name: "Grid", path: "/ui-kit/grid"},
            {name: "Avtar", path: "/ui-kit/avtar"},
            {name: "Tabs", path: "/ui-kit/tabs"},
            {name: "Accordions", path: "/ui-kit/accordions"},
            {name: "Progress", path: "/ui-kit/progress"},
            {name: "Notifications", path: "/ui-kit/notifications"},
            {name: "Lists", path: "/ui-kit/lists"},
            {name: "Helper Classes", path: "/ui-kit/helper-classes"},
            {name: "Background", path: "/ui-kit/background"},
            {name: "Divider", path: "/ui-kit/divider"},
            {name: "Ribbons", path: "/ui-kit/ribbons"},
            {name: "Editor", path: "/ui-kit/editor"},
            {name: "Collapse", path: "/ui-kit/collapse"},
            {name: "Shadow", path: "/ui-kit/shadow"},
            {name: "Wrapper", path: "/ui-kit/wrapper"},
            {name: "Bullet", path: "/ui-kit/bullet"},
            {name: "Placeholder", path: "/ui-kit/placeholder"},
            {name: "Alignment Things", path: "/ui-kit/alignment-thing"}
        ],
    },
    {
        type: "dropdown",
        iconClass: "ph-duotone ph-briefcase-metal",
        name: "Advanced UI",
        badgeCount: "12+",
        collapseId: "advance-ui",
        path: '/dashboard',
        children: [
            {name: "Modals", path: "/advance_ui/modals"},
            {name: "OffCanvas Toggle", path: "/advance_ui/offcanvas_toggle"},
            {name: "Sweet Alert", path: "/advance_ui/sweet_alert"},
            {name: "Scrollbar", path: "/advance_ui/scrollbar"},
            {name: "Spinners", path: "/advance_ui/spinners"},
            {name: "Animation", path: "/advance_ui/animation"},
            {name: "Video Embed", path: "/advance_ui/video_embed"},
            {name: "Tour", path: "/advance_ui/tour"},
            {name: "Slider", path: "/advance_ui/slider"},
            {name: "Bootstrap Slider", path: "/advance_ui/bootstrap_slider"},
            {name: "Scrollpy", path: "/advance_ui/scrollpy"},
            {name: "Tooltip & Popovers", path: "/advance_ui/tooltip_popovers"},
            {name: "Rating", path: "/advance_ui/rating"},
            {name: "Prismjs", path: "/advance_ui/prismjs"},
            {name: "Count Down", path: "/advance_ui/count_down"},
            {name: "Count Up", path: "/advance_ui/count_up"},
            {name: "Draggable", path: "/advance_ui/draggable"},
            {name: "Tree View", path: "/advance_ui/tree_view"},
            {name: "Block Ui", path: "/advance_ui/block_ui"},
        ],
    },
    {
        type: "dropdown",
        iconClass: "ph-duotone ph-shapes",
        name: "Icons",
        collapseId: "icons",
        path: '/icons',
        children: [
            {name: "Fontawesome", path: "/icons/fontawesome"},
            {name: "Flag", path: "/icons/flag"},
            {name: "Tabler", path: "/icons/tabler"},
            {name: "Weather", path: "/icons/weather"},
            {name: "Animated", path: "/icons/animated"},
            {name: "Iconoir", path: "/icons/iconoir"},
            {name: "Phosphor", path: "/icons/phosphor"},
        ],
    },
    {
        name: "Misc",
        path: '/misc',
        iconClass: "ph-duotone ph-certificate",
    },
    {
        type: "dropdown",
        title: "Map & Charts",
        iconClass: "ph-duotone ph-map-pin-line",
        collapseId: "maps",
        name: "Map & Charts",
        path: '/map-charts',
        children: [
            {name: "Google Maps", path: "/map/google_maps"},
            {name: "Leaflet map", path: "/map/leaflet_map"},
            {name: "Vector map", path: "/map/vector_map"},
        ],
    },
    {
        type: "dropdown",
        iconClass: "ph-duotone ph-chart-pie-slice",
        collapseId: "chart",
        name: "Chart",
        path: '/chartjs-page',
        children: [
            {
                name: "Chart",
                path: '/chart/chart_js',
                // collapseId: "chartjs-page" ,
            },
            {
                name: "Apexcharts",
                path: "/Apexcharts.html",
                collapseId: "apexcharts-page",
                children: [
                    {name: "Line", path: "/chart/apexcharts/line"},
                    {name: "Area", path: "/chart/apexcharts/area"},
                    {name: "Column", path: "/chart/apexcharts/column"},
                    {name: "Bar", path: "/chart/apexcharts/bar"},
                    {name: "Mixed", path: "/chart/apexcharts/mixed"},
                    {name: "Timeline & Range-Bars", path: "/chart/apexcharts/timeline_range_bars"},
                    {name: "Candlestick", path: "/chart/apexcharts/candlestick"},
                    {name: "Boxplot", path: "/chart/apexcharts/boxplot"},
                    {name: "Bubble", path: "/chart/apexcharts/bubble"},
                    {name: "Scatter", path: "/chart/apexcharts/scatter"},
                    {name: "Heatmap", path: "/chart/apexcharts/heatmap"},
                    {name: "Treemap", path: "/chart/apexcharts/treemap"},
                    {name: "Pie", path: "/chart/apexcharts/pie"},
                    {name: "Radial bar", path: "/chart/apexcharts/radial_bar"},
                    {name: "Radar", path: "/chart/apexcharts/radar_chart"},
                ],
            },
        ],
    },
    {
        type: "dropdown",
        title: "Table & forms",
        iconClass: "ph-duotone ph-table",
        collapseId: "table",
        name: "Table",
        path: '/table',
        children: [
            {name: "Basic Table", path: "/table/basictable"},
            {name: "Data Table", path: "/table/data_table"},
            {name: "List Js", path: "/table/list_js"},
            {name: "Advance Table", path: "/table/advance_table"}
        ],
    },
    {
        type: "dropdown",
        iconClass: "ph-duotone ph-cardholder",
        collapseId: "forms",
        name: "Forms elements",
        path: '/forms',
        children: [
            {name: "Form Validation", path: "/forms_elements/form_validation"},
            {name: "Base Input", path: "/forms_elements/base_input"},
            {name: "Checkbox & Radio", path: "/forms_elements/checkbox_radio"},
            {name: "Input Groups", path: "/forms_elements/input_groups"},
            {name: "Input Masks", path: "/forms_elements/input_masks"},
            {name: "Floating Labels", path: "/forms_elements/floating_labels"},
            {name: "Datetimepicker", path: "/forms_elements/datetimepicker"},
            {name: "Touch spin", path: "/forms_elements/touch_spin"},
            {name: "Select2", path: "/forms_elements/select2"},
            {name: "Switch", path: "/forms_elements/switch"},
            {name: "Range Slider", path: "/forms_elements/range_slider"},
            {name: "Typeahead", path: "/forms_elements/typeahead"},
            {name: "Textarea", path: "/forms_elements/textarea"},
            {name: "Clipboard", path: "/forms_elements/clipboard"},
            {name: "File Upload", path: "/forms_elements/file_upload"},
            {name: "Dual List Boxes", path: "/forms_elements/dual_list_boxes"},
            {name: "Default Forms", path: "/forms_elements/default_forms"}
        ],
    },
    {
        type: "dropdown",
        iconClass: "ph-duotone ph-hand-heart",
        name: "Ready to use",
        badgeCount: "new",
        collapseId: "ready_to_use",
        path: '/ready_to_use',
        children: [
            {name: "Form Wizards", path: "/ready_to_use/form_wizards"},
            {name: "Form Wizards 1", path: "/ready_to_use/form_wizard_1"},
            {name: "Form Wizards 2", path: "/ready_to_use/form_wizard_2"},
            {name: "Ready To Use Form", path: "/ready_to_use/ready_to_use_form"},
            {name: "Ready To Use Tables", path: "/ready_to_use/ready_to_use_tables"},

        ],
    },
    {
        type: "dropdown",
        title: "Pages",
        iconClass: "ph-duotone ph-notebook",
        name: "Auth Pages",
        collapseId: "auth_pages",
        path: '/auth_pages',
        children: [
            {name: "Sign In", path: "/admin-pages/auth_pages/sign_in"},
            {name: "Sign In with Bg-image", path: "/admin-pages/auth_pages/sign_in_with_bg_image"},
            {name: "Sign Up", path: "/admin-pages/auth_pages/sign_up"},
            {name: "Sign Up with Bg-image", path: "/admin-pages/auth_pages/sign_up_with_bg_image"},
            {name: "Password Reset", path: "/admin-pages/auth_pages/password_reset"},
            {name: "Password Reset with Bg-image", path: "/admin-pages/auth_pages/password_reset_with_bg_image"},
            {name: "Password Create", path: "/admin-pages/auth_pages/password_create"},
            {name: "Password Create with Bg-image", path: "/admin-pages/auth_pages/password_create_with_bg_image"},
            {name: "Lock Screen", path: "/admin-pages/auth_pages/lock_screen"},
            {name: "Lock Screen with Bg-image", path: "/admin-pages/auth_pages/lock_screen_with_bg_image"},
            {name: "Two Step Verification", path: "/admin-pages/auth_pages/two_step_verification"},
            {
                name: "Two Step Verification with Bg-image",
                path: "/admin-pages/auth_pages/two_step_verification_with_bg_image"
            },

        ],
    },
    {
        type: "dropdown",
        iconClass: "ph-duotone ph-warning-octagon",
        name: "Error pages",
        collapseId: "error_pages",
        path: '/error_pages',
        children: [
            {name: "Bad Request", path: "/admin-pages/error_pages/bad_request"},
            {name: "Forbidden", path: "/admin-pages/error_pages/forbidden"},
            {name: "Not Found", path: "/admin-pages/error_pages/not_found"},
            {name: "Internal Server Error", path: "/admin-pages/error_pages/internal_server"},
            {name: "Service Unavailable", path: "/admin-pages/error_pages/service_unavailable"},
        ],
    },
    {
        type: "dropdown",
        iconClass: "ph-duotone ph-newspaper",
        name: "Other pages",
        collapseId: "other_pages",
        path: '/other_pages',
        children: [
            {name: "Blank", path: "/admin-pages/other_pages/blank"},
            {name: "Maintenance", path: "/admin-pages/other_pages/maintenance"},
            {name: "Coming Soon", path: "/admin-pages/other_pages/coming_soon"},
            {name: "Landing Pages", path: "/admin-pages/other_pages/landing_page"},
            {name: "Sitemap", path: "/admin-pages/other_pages/sitemap"},
            {name: "Privacy Policy", path: "/admin-pages/other_pages/privacy_policy"},
            {name: "Terms & Conditions", path: "/admin-pages/other_pages/terms_condition"},
        ],
    },
    {
        type: "dropdown",
        title: "Others",
        iconClass: "ph-duotone ph-number-circle-two",
        name: "2 level",
        collapseId: "level",
        path: '/level',
        children: [
            {name: "Blank", path: "/"},
            {
                name: "Another level",
                path: "/",
                collapseId: "level2",
                children: [
                    {name: "Blank", path: ""},
                ],
            },
        ],
    },
    {
        name: "Support",
        path: 'mailto:teqlathemes@gmail.com.',
        iconClass: "ph-duotone ph-chats",
    },
];
